[package]
name = "tile_rack_ggez"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6"
mint = "0.5.6"
itertools = "0.10.1"